name: Deploy PostgreSQL with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start PostgreSQL container
        run: |
          docker compose up -d
          
      - name: Check running containers
        run: |
          docker ps
