name: Deploy ETL Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 19 * * *'  # Runs every day at 19:00 UTC (8 PM CET in winter)

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:   # Injecting secrets into the environment
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start PostgreSQL container
        run: |
          docker compose up -d
          
      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to start..."
          sleep 15  # wait for DB to be fully ready

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Ingestion and MasterData
        run: |
          cd scripts
          python ingestion.py
          python masterdata.py

      - name: Run Quality Checks
        run: |
          cd scripts
          python qualitychecks.py

      - name: Run Transformations
        run: |
          cd scripts
          python transformations.py
