name: Deploy PostgreSQL with Docker and Connect via Python

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start PostgreSQL container
        run: |
          docker compose up -d
          
      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to start..."
          sleep 15 # wait for DB to be ready (adjust if needed)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or 3.10/3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to connect to Postgres
        run: |
          python connect_postgres.py
